panda_follower_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_follower_joint1
    - panda_follower_joint2
    - panda_follower_joint3
    - panda_follower_joint4
    - panda_follower_joint5
    - panda_follower_joint6
    - panda_follower_joint7
  constraints:
    goal_time: 0.5
    panda_follower_joint1: { goal: 0.05}
    panda_follower_joint2: { goal: 0.05}
    panda_follower_joint3: { goal: 0.05}
    panda_follower_joint4: { goal: 0.05}
    panda_follower_joint5: { goal: 0.05}
    panda_follower_joint6: { goal: 0.05}
    panda_follower_joint7: { goal: 0.05}

panda_follower_effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_follower_joint1
    - panda_follower_joint2
    - panda_follower_joint3
    - panda_follower_joint4
    - panda_follower_joint5
    - panda_follower_joint6
    - panda_follower_joint7
  gains:
    panda_follower_joint1: { p: 600, d: 30, i: 0 }
    panda_follower_joint2: { p: 600, d: 30, i: 0 }
    panda_follower_joint3: { p: 600, d: 30, i: 0 }
    panda_follower_joint4: { p: 600, d: 30, i: 0 }
    panda_follower_joint5: { p: 250, d: 10, i: 0 }
    panda_follower_joint6: { p: 150, d: 10, i: 0 }
    panda_follower_joint7: { p: 50, d: 5, i: 0 }
  constraints:
    goal_time: 0.5
    panda_follower_joint1: { goal: 0.05}
    panda_follower_joint2: { goal: 0.05}
    panda_follower_joint3: { goal: 0.05}
    panda_follower_joint4: { goal: 0.05}
    panda_follower_joint5: { goal: 0.05}
    panda_follower_joint6: { goal: 0.05}
    panda_follower_joint7: { goal: 0.05}

panda_follower_state_controller:
  type: franka_control/FrankaStateController
  publish_rate: 30  # [Hz]
  joint_names:
    - panda_follower_joint1
    - panda_follower_joint2
    - panda_follower_joint3
    - panda_follower_joint4
    - panda_follower_joint5
    - panda_follower_joint6
    - panda_follower_joint7
  arm_id: panda_follower

panda_follower_joint_velocity_controller:
    type: franka_example_controllers/JointVelocityExampleController
    joint_names:
        - panda_follower_joint1
        - panda_follower_joint2
        - panda_follower_joint3
        - panda_follower_joint4
        - panda_follower_joint5
        - panda_follower_joint6
        - panda_follower_joint7